# site settings
title: Jackson Han
subtitle:
email: jacksonhan@opayq.com
description: Software projects, research recreations, and engineering notes.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://jtrcode.github.io # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 40

# social settings
500px_url:
facebook_url:
github_url: https://github.com/JTRcode
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/jackson-han
pinterest_url:
slack_url:
twitter_url:

plugins:
  - jekyll-sitemap
  
# build settings
markdown: kramdown

sass:
  style: compressed

# Google services
google_analytics: UA-176724597-1
