# site settings
title: Jackson
subtitle: by HTML5 UP
email: jacksonhan@opayq.com
description: This site acts as a museum of what I have done<br /> and for you to learn more about me.
baseurl: "JacksonHan" # the subpath of your site, e.g. /blog
url: https://jtrcode.github.io # the base hostname & protocol for your site
author:
street_address: 1265 Military Trail
city: Scarborough
state: ON
zip_code: M1C 1A4
country: Canada
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 15

# social settings
500px_url:
facebook_url: https://facebook.com/jackson.han.338
github_url: https://github.com/JTRcode/JacksonHan
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/jackson-han
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
